# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b997c3b73f4923913c995fe720299dc67db9ffb8ba1a5f6aa77dd22684600d9cb2d8b161527f110b2b5971b8afca9f2a9b6a841dfebb29631ee2abac1070b625

test:
  secret_key_base: cb1a87726a7aa7fa26d73493d3ee961e3aad57401a4e11288a34af20d2759bba59ce3306a04fab2392e439db227da06afb28da178b59ab3781d0a1c1502c7061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
